version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "install step"
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r9 ../deployment-package.zip .
      - zip -g ../deployment-package.zip index_photos.py
      - zip -g ../deployment-package.zip search_photos.py
      - echo "Listing current directory contents:"
      - ls -la
      - aws s3 sync ./frontend/ "s3://frontendcc3"
      - cd ..
      - echo "Listing current directory contents:"
      - ls -la
      
      
  post_build:
    commands:
      - echo "Updating index-photo lambda function"
      - aws lambda update-function-code --function-name index_photos --zip-file fileb://deployment-package.zip
      - echo "Updating search-photo lambda function"
      - aws lambda update-function-code --function-name search_photos --zip-file fileb://deployment-package.zip
      - echo "post_build step"
